# Generated by Django 5.1.7 on 2025-03-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NumeroDia', models.IntegerField()),
                ('NombreDia', models.CharField(max_length=200)),
                ('FechaRegistro', models.DateTimeField(verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'DiasSemana',
            },
        ),
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NumeroMes', models.IntegerField()),
                ('NombreMes', models.CharField(max_length=200)),
                ('FechaRegistro', models.DateTimeField(verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'Meses',
            },
        ),
    ]
