# Generated by Django 5.1.7 on 2025-03-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WomenPeriodApp', '0002_calendario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diassemana',
            name='NumeroDia',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='meses',
            name='NumeroMes',
            field=models.IntegerField(unique=True),
        ),
    ]
