# Generated by Django 5.1.7 on 2025-03-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WomenPeriodApp', '0004_alter_diassemana_numerodia_alter_meses_numeromes'),
    ]

    operations = [
        migrations.AddField(
            model_name='diassemana',
            name='Abreviatura',
            field=models.CharField(default='LU', max_length=2),
        ),
    ]
