# Generated by Django 5.1.7 on 2025-03-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WomenPeriodApp', '0005_diassemana_abreviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='AnnoCalendario',
            field=models.IntegerField(default=2025),
        ),
    ]
