# Generated by Django 5.1.7 on 2025-03-13 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WomenPeriodApp', '0006_calendario_annocalendario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioDias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ValorFecha', models.DateField(verbose_name='Fecha')),
                ('DiaValorFecha', models.IntegerField()),
                ('MesValorFecha', models.IntegerField()),
                ('AnnoValorFecha', models.IntegerField(default=2025)),
                ('PerteneceMes', models.BooleanField(default=True)),
                ('Orden', models.IntegerField()),
                ('FechaRegistro', models.DateTimeField(verbose_name='fecha registro')),
                ('Calendario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WomenPeriodApp.calendario')),
                ('DiaSemana', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WomenPeriodApp.diassemana')),
            ],
            options={
                'db_table': 'CalendarioDias',
            },
        ),
    ]
