# Generated by Django 5.1.7 on 2025-03-18 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WomenPeriodApp', '0007_calendariodias'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionesActivas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('fecha_conexion', models.DateTimeField(verbose_name='fecha ultma conexion')),
                ('token_session', models.CharField(blank=True, max_length=100)),
                ('dispositivo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'SesionesActivas',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('apellido_usuario', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('numero_telefono', models.CharField(blank=True, max_length=20)),
                ('ultima_conexion', models.DateTimeField(verbose_name='fecha ultma conexion')),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Versiones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('link_descarga', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(verbose_name='fecha creacion')),
            ],
            options={
                'db_table': 'Versiones',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_recuperacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(verbose_name='fecha creacion')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='fecha vencimiento')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='fecha vencimiento')),
                ('codigo_tipo', models.IntegerField(choices=[(1, 'Cambio de contraseña'), (2, 'Recuperación de contraseña')], default=2)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WomenPeriodApp.usuarios')),
            ],
            options={
                'db_table': 'SolicitudPassword',
            },
        ),
    ]
