# Generated by Django 5.1.7 on 2025-03-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WomenPeriodApp', '0008_sesionesactivas_usuarios_versiones_solicitudpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
