# Generated by Django 5.1.7 on 2025-03-19 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WomenPeriodApp', '0009_usuarios_push_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelIntensidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreIntensidad', models.CharField(max_length=100)),
                ('NumeroNivel', models.IntegerField()),
                ('FechaRegistro', models.DateTimeField(verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'NivelIntensidad',
            },
        ),
        migrations.CreateModel(
            name='TipoMarca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTipoMarca', models.CharField(max_length=100)),
                ('FechaRegistro', models.DateTimeField(verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'TipoMarca',
            },
        ),
        migrations.CreateModel(
            name='MarcasUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('FechaRegistro', models.DateTimeField(verbose_name='fecha registro')),
                ('DesdeDia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marcas_desde_dia', to='WomenPeriodApp.calendariodias')),
                ('HastaDia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marcas_hasta_dia', to='WomenPeriodApp.calendariodias')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WomenPeriodApp.usuarios')),
                ('Intensidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WomenPeriodApp.nivelintensidad')),
                ('TipoMarca', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WomenPeriodApp.tipomarca')),
            ],
            options={
                'db_table': 'MarcasUsuario',
            },
        ),
    ]
