# Generated by Django 5.1.7 on 2025-04-08 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WomenPeriodApp', '0010_nivelintensidad_tipomarca_marcasusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasPreviosAvisoPeriodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CantidadDias', models.IntegerField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WomenPeriodApp.usuarios')),
            ],
            options={
                'db_table': 'DiasPreviosAvisoPeriodo',
            },
        ),
    ]
