# Generated by Django 5.1.7 on 2025-04-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WomenPeriodApp', '0011_diaspreviosavisoperiodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaspreviosavisoperiodo',
            name='FechaRegistro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha registro'),
        ),
    ]
